--@BLOCK
CREATE DATABASE CAR_SERVICE_MEDIATOR;
USE CAR_SERVICE_MEDIATOR;
--@BLOCK
CREATE TABLE  ADDRESS_ (
    ID INT,
    CITY VARCHAR(128) NOT NULL ,
    STREET varchar(128) NOT NULL ,  
    COUNTRY VARCHAR(128)  NULL ,
    PRIMARY KEY(ID)
);
--@BLOCK
CREATE TABLE CUSTOMERS(
	ID INT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(16) NOT NULL,
    LAST_NAME VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    ADDRESS_ID INT,
    CREDAT_CARD_NUM INT,
    OWENED_CARS_ID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS_(ID)
);
--@BLOCK
CREATE TABLE SERVICES(
    NAME_ VARCHAR(64),
    DESCRIPTION_ TEXT NOT NULL,
    TOP_PROVIDER INT,
    PRIMARY KEY(NAME_),
);
--@BLOCK
CREATE TABLE SERVICE_PROVIDERS(
    ID INT AUTO_INCREMENT,
    NAME_ VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    WEBSITE VARCHAR(255),
    ADDRESS_ID INT,
    RATE FLOAT, --DEFOALT = 0
    SERVICE_NAME_ VARCHAR(255),
    PRIMARY KEY(ID),
    FOREIGN KEY(SERVICE_NAME_) REFERENCES SERVICES(NAME_),
    FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS_(ID)
);
--@BLOCK
CREATE TABLE CARS(
    ID INT AUTO_INCREMENT,
    CAR_NUM VARCHAR(16) NOT NULL UNIQUE,
    CAR_TRADE_MARK VARCHAR(16) NOT NULL,
    CAR_MODEL VARCHAR(16) NOT NULL,
    CAR_CLASSFICATION VARCHAR(16) NOT NULL,
    MADE_IN VARCHAR(16) NOT NULL,
    MOTOR_NUM INT NOT NULL,
    CHASEH_NUM INT NOT NULL,
    OWNER_ID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY(OWNER_ID) REFERENCES CUSTOMERS(ID)
);
--@BLOCK
CREATE TABLE PILLS(
    ID INT AUTO_INCREMENT,
    PRICE FLOAT,
    ORDER_DATE DATETIME,
    ORDER_FINISH_DATE DATETIME,
    CUSTOMER_ID INT NOT NULL,
    CAR_ID INT NOT NULL,
    PROVIDOR_ID INT NOT NULL,
    SERVICE_NAME_ VARCHAR(64),
    PRIMARY KEY(ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY(CAR_ID) REFERENCES CARS(ID),
    FOREIGN KEY(PROVIDOR_ID) REFERENCES SERVICE_PROVIDERS(ID),
    FOREIGN KEY(SERVICE_NAME_) REFERENCES SERVICES(NAME_)
);
--@BLOCK
ALTER TABLE
    SERVICES ADD CONSTRAINT SERVICES_TOP_PROVIDER_FOREIGN FOREIGN KEY(TOP_PROVIDER) REFERENCES SERVICE_PROVIDERS(ID);
ALTER TABLE
    CUSTOMERS ADD CONSTRAINT CUSTOMERS_OWENED_CARS_ID_FOREIGN FOREIGN KEY(OWENED_CARS_ID) REFERENCES CARS(ID);

